### ISSUE TITLE
Интеграция ML

### ISSUE THREAD

**Issue by quaterhalfbro** [M3100Team/firstlab#17]
Выбрать способ для интеграции ML в проект

**Comment by goosescout** [comment]
@quaterhalfbro, напиши тут в комменте что вы решили в итоге, а то задача в Done, а что done - непонятно))

**Comment by quaterhalfbro** [comment]
Решили, что просто из ML репозитория перенесем в main репозиторий функцию, принимающую PIL.Image и возвращающую вероятность принадлежности работы к нормальным.
