### ISSUE TITLE
Подключение API регистрации к фронтенду

### ISSUE THREAD

**Issue by goosescout** [M3100Team/firstlab#29]
Подключить к фронтенду написанное API регистрации, которое будет запускаться на локальном сервере

**Comment by goosescout** [comment]
@sadfun , получаю вот такую ошибку, когда пытаюсь запустить сервер (он, кстати, запускается не через `uvicorn run main:app`, а через `uvicorn main:app`)

![image](https://user-images.githubusercontent.com/48148194/141613578-3d60cf92-c19e-4d18-b7e9-490f73aec827.png)

Я так понимаю, мне надо сделать `.env` файл, где будет ссылка для подключения к базе?

**Comment by sadfun** [comment]
Для работы сервера нужны значения `MONGO_URI` (строка для подключения к базе) и `SECRET_KEY` (любая секретная и длинная строка, с её помощью хешируются токены) в **переменных окружения**. Это вовсе не обязательно файл `.env`, есть много разных способов их задавать. Способ для винды стоит загуглить отдельно

**Comment by sadfun** [comment]
К слову, именно в переменных окружения и принято хранить чувствительные данные, например токены и пароли

**Comment by goosescout** [comment]
А ты мне эти `MONGO_URI` и `SECRET_KEY` дашь?)

**Comment by sadfun** [comment]
`SECRET_KEY` пока можно ставить любой. Для того, чтобы был `MONGO_URI`, надо где-то поднять mongoDB. Как вариант - сказать с сайта Community-версию и запустить в фоне, тогда `MONGO_URI=mongodb://127.0.0.1:27017`

**Comment by goosescout** [comment]
На данный момент существуют следующие проблемы, которые мешают работе API:
- При запросе к `/login` возвращается только токен. Нужно сделать чтобы приходило ещё имя и группа
- Токены не работают. При запросе к `/me` по только что полученному токену получаю `"Could not validate credentials"`
- В базе данных нету поля под группы
