### ISSUE TITLE
Организовать основную структуру проекта

### ISSUE THREAD

**Issue by goosescout** [M3100Team/firstlab#7]
Определить основную структура проекта:
- [x] Методология, по которой ведётся работа с github
- [x] Нейминг веток
- [x] Нейминг папок

**Comment by sadfun** [comment]
Увы, я в Германии)
Благо нашёл себе норм интернет, так что в дискорд могу

**Comment by goosescout** [comment]
1. Методология: Github Flow: https://guides.github.com/introduction/flow/
2. По Github Flow
3. Папки:
    * frontend/ - папка фронтенда
    * backend/ - папка бэкенда
